[package]
name = "tetris"
version = "0.1.0"
authors = ["Manpreet Singh Matharu <matharumanpreet00@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2" }
rand = "0.5.5"